import 'dart:convert';
import 'dart:typed_data';

// ============================================================
// UNMASK CODEC — position_xor family (generated by tool/forge)
// ============================================================
// Do NOT hand-edit. Regenerate via `dart run tool/forge/mint.dart`.
// ============================================================

const List<int> _saltBytes = <int>[
  0xD7, 0x55, 0x78, 0x74, 0xD6, 0xA9, 0xB9, 0xD3,
  0xBD, 0xC6, 0xF8, 0x63, 0x0A, 0x09, 0xAA, 0x26,
  0x5B, 0xF7, 0x39, 0xB1, 0xA0, 0xA8, 0x1D,
];
const int _streamLen = 34;

const int _weylStep = 0x9E3779B1;

Uint8List _keystream() {
  int accumulator = 0x243F6A88;
  for (int i = 0; i < _saltBytes.length; i++) {
    accumulator = (accumulator + _saltBytes[i] * (i + 1) + _weylStep) &
        0xFFFFFFFF;
  }
  int state = accumulator == 0 ? _weylStep : accumulator;
  final Uint8List stream = Uint8List(_streamLen);
  for (int i = 0; i < _streamLen; i++) {
    state ^= (state << 13) & 0xFFFFFFFF;
    state ^= state >> 17;
    state ^= (state << 5) & 0xFFFFFFFF;
    state &= 0xFFFFFFFF;
    stream[i] = (state >> 16) & 0xFF;
  }
  return stream;
}

final Uint8List _stream = _keystream();

int _positionMask(int i) => ((i * _weylStep) >> 16) & 0xFF;

String reveal(List<int> encoded) {
  if (encoded.isEmpty) return '';
  final Uint8List out = Uint8List(encoded.length);
  for (int i = 0; i < encoded.length; i++) {
    out[i] = (encoded[i] ^ _stream[i % _streamLen] ^ _positionMask(i)) & 0xFF;
  }
  return utf8.decode(out);
}
