import '../codec/veil_codec.dart';

// ============================================================
// VEILED BYTES — generated by tool/forge/mint.dart
// ============================================================
// Do NOT hand-edit. Re-run the forge to change any value here.
// ============================================================

const List<int> _endpointUrl = <int>[
  218, 214, 166, 168, 28, 45, 23, 47, 253, 235, 38, 106,
  26, 196, 176, 135, 238, 81, 38, 156, 205, 78, 45, 216,
  250, 160, 80, 108, 184, 139, 95, 248, 156,
];

const List<int> _gcdBaseUrl = <int>[
  218, 214, 166, 168, 28, 45, 23, 47, 248, 228, 35, 99,
  27, 205, 241, 147, 240, 69, 123, 150, 200, 89, 35, 133,
  177, 167, 88, 100, 184, 145, 72, 229, 139, 161, 128, 108,
  46, 30, 239, 5, 190, 73, 75, 17, 203, 130, 62,
];

const List<int> _attributionKey = <int>[
  197, 155, 163, 176, 53, 89, 114, 88, 219, 240, 10, 117,
  43, 144, 175, 159, 202, 102, 95, 189, 146, 79,
];

const List<int> _messagingProject = <int>[
  134, 146, 230, 225, 92, 37, 9, 49, 167, 180, 112, 38,
];

const List<int> _uaProduct = <int>[
  255, 205, 168, 177, 3, 123, 89, 47, 170, 169, 119,
];

const List<int> _uaLinuxOpen = <int>[
  154, 238, 187, 182, 26, 111, 3, 32, 222, 233, 35, 98,
  16, 207, 187,
];

const List<int> _uaBuildLabel = <int>[
  146, 224, 167, 177, 3, 115, 23,
];

const List<int> _uaBuildClose = <int>[
  155,
];

const List<int> _uaEngineLabel = <int>[
  146, 227, 162, 168, 3, 114, 111, 101, 253, 204, 46, 100,
  80,
];

const List<int> _uaEngineTail = <int>[
  146, 138, 153, 144, 59, 90, 116, 44, 191, 235, 46, 123,
  26, 134, 152, 151, 227, 94, 103, 217,
];

const List<int> _uaChromeLabel = <int>[
  146, 225, 186, 170, 0, 122, 93, 47,
];

const List<int> _uaMobileSafari = <int>[
  146, 239, 189, 186, 6, 123, 93, 32, 204, 230, 33, 113,
  13, 207, 240,
];

const List<int> _chromeVersion = <int>[
  131, 150, 235, 246, 95, 57, 15, 55, 171, 181, 105, 38,
  71,
];

const List<int> _webkitVersion = <int>[
  135, 145, 229, 246, 92, 33,
];

const List<int> _jsSafeAreaScript = <int>[];

const List<int> _jsKeyboardScript = <int>[];

const List<int> _jsAutoplayScript = <int>[];

String unlockEndpointUrl() => reveal(_endpointUrl);
String unlockGcdBaseUrl() => reveal(_gcdBaseUrl);
String unlockAttributionKey() => reveal(_attributionKey);
String unlockMessagingProject() => reveal(_messagingProject);

String unlockUaProduct() => reveal(_uaProduct);
String unlockUaLinuxOpen() => reveal(_uaLinuxOpen);
String unlockUaBuildLabel() => reveal(_uaBuildLabel);
String unlockUaBuildClose() => reveal(_uaBuildClose);
String unlockUaEngineLabel() => reveal(_uaEngineLabel);
String unlockUaEngineTail() => reveal(_uaEngineTail);
String unlockUaChromeLabel() => reveal(_uaChromeLabel);
String unlockUaMobileSafari() => reveal(_uaMobileSafari);
String unlockChromeVersion() => reveal(_chromeVersion);
String unlockWebkitVersion() => reveal(_webkitVersion);

String unlockJsSafeAreaScript() => reveal(_jsSafeAreaScript);
String unlockJsKeyboardScript() => reveal(_jsKeyboardScript);
String unlockJsAutoplayScript() => reveal(_jsAutoplayScript);

String unlockGcdCallUrl(String applicationId, String deviceId) {
  final String base = unlockGcdBaseUrl();
  if (base.isEmpty) return '';
  return '$base$applicationId?devkey=${unlockAttributionKey()}&device_id=$deviceId';
}
